[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "tax-filing-backend"

[services.variables]
PORT = "8080"