[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
startCommand = "npm start"

[build.env]
NODE_ENV = "production"

[deploy.env]
NODE_ENV = "production"
PORT = "8080"
